// import MenuList from "../components/MenuList";
export const SiteData = {
  title: "MySite",
  auth: [
    {
      text: "Join",
      link: "/signup",
      icon: "",
      // submenu: [
      //   { text: "Register", link: "/register", icon: "" },
      //   { text: "Login", link: "/login", icon: "", class: "" },
      // ],
    },
  ],
  PublicMenu: [
    {
      text: "About",
      link: "about",
      icon: "bi-list",
      submenu: [
        { text: "Our Team", link: "/about/team", icon: "bi-list" },
        { text: "Our Vision", link: "/about/vision", icon: "bi-list" },
        { text: "Pricing", link: "/about/pricing", icon: "" },
      ],
    },
    { text: "Services", link: "/services/discover", icon: "" },
    // Private Menu Shift
    // { text: "SignUp", link: "/signup", icon: "" },
    { text: "Learning", link: "/learning/home", icon: "" },
    { text: "eCommerce", link: "/ecommerce", icon: "" },
    { text: "Task", link: "/tasks", icon: "" },
    { text: "Budget", link: "/budget", icon: "" },
    { text: "Posts", link: "/posts", icon: "" },
  ],
  PrivateMenus: {
    NavMenu: [],
    ServiceTabMenu: [
      { text: "Discover", link: "/services/discover", icon: "bi-android2" },
      { text: "Prepaid", link: "/services/prepaid", icon: "bi-sim" },
      { text: "Recharge", link: "/services/recharge", icon: "bi-phone" },
      { text: "PayBills", link: "/services/paybills", icon: "bi-cash-stack" },
    ],
    LearningTabMenu: [
      { text: "Components", link: "/learning/home", icon: "bi-play-btn" },
      { text: "Trending", link: "/learning/trending", icon: "bi-fire" },
      { text: "Gaming", link: "/learning/gaming", icon: "bi-controller" },
      { text: "Music", link: "/learning/music", icon: "bi-music-note-list" },
      { text: "Channel", link: "/learning/channel", icon: "bi-person-badge" },
    ],
    ECommerceTabMenu: [
      { text: "Trending", link: "/ecommerce/trending", icon: "bi-fire" },
      { text: "Food", link: "/ecommerce/food", icon: "bi-play-btn" },
      { text: "Sports", link: "/ecommerce/sports", icon: "bi-controller" },
      {
        text: "Itspecs",
        link: "/ecommerce/itspecs",
        icon: "bi-music-note-list",
      },
    ],
    BudgetTabMenu: [
      { text: "MongoDb", link: "/budget", icon: "bi-list" },
      { text: "Serverless", link: "/budget/serverless", icon: "bi-list" },
    ],
    // YTCards: [],
  },
  userProfile: [
    { text: "My Profile", icon: "", link: "#" },
    { text: "Setting", icon: "", link: "#" },
  ],
  footerLinks: [
    {
      text: "Support",
      link: "#",
      icon: "bi-list",
      submenu: [
        { text: "Contact", link: "support/contact", icon: "bi-list" },
        { text: "FAQ", link: "support/faq", icon: "" },
      ],
    },
    {
      text: "Policies",
      link: "#",
      icon: "",
      submenu: [
        { text: "Privacy", link: "/privacy", icon: "bi-list" },
        { text: "Terms & Conditions", link: "/termsconditions", icon: "" },
      ],
    },
  ],
  SocialMedia: [
    { text: "Facebook", link: "#", icon: "bi-facebook" },
    { text: "Twitter", link: "#", icon: "bi-twitter" },
    { text: "Instagram", link: "#", icon: "bi-instagram" },
    { text: "Youtube", link: "#", icon: "bi-youtube" },
  ],
  ComponentData: {
    HomeCorousal: [
      {
        text: "P",
        link: "#",
        class: "",
        image: "https://www.jio.com/cricket-bonanza-1b.webp ",
      },
      {
        text: "P",
        link: "#",
        class: "",
        image: " https://jep-asset.akamaized.net/jio/webp/homepage/dive-masthd-desk-v3.webp ",
      },
      {
        text: "P",
        link: "#",
        class: "",
        image: " https://www.jio.com/jioplus-masthead-desk-v1.png",
      },
    ],
    Corousal: [
      {
        text: "P",
        link: "/about",
        class: "",
        image: "https://www.jio.com/new-banner.png",
      },
      {
        text: "P",
        link: "#",
        class: "",
        image: "https://www.jio.com/homepage-desk.png",
      },
      {
        text: "P",
        link: "#",
        class: "",
        image: "https://www.jio.com/new-banner.png",
      },
    ],
    FoodMenu: [
      {
        title: "Aut Luia",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-2.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Est Eligendi",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-3.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Eos Luibusdam",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-4.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Eos Luibusdam",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-5.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Laboriosam Direva",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-6.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Aut Luia",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-2.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Est Eligendi",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-3.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Eos Luibusdam",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-4.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Eos Luibusdam",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-5.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
      {
        title: "Laboriosam Direva",
        src: "https://bootstrapmade.com/demo/templates/Yummy/assets/img/menu/menu-item-6.png",
        text: "Lorem, deren, trataro, filede, nerada",
      },
    ],
    YTVids: [
      {
        User: "Robiul Hossain Robin",
        Channelink: "https://www.youtube.com/channel/UCM6WhjDnZ-6ELNuySC5AbzQ",
        Title: "Relationship with Populate in Node JS, Mongoose, and MongoDB - Relationship with populate in Node JS",
        VideoLink: "https://www.youtube.com/watch?v=mSQwg_H2T7c",
        Category: "Music",
        Thumb: "https://i.ytimg.com/vi/mSQwg_H2T7c/hq720.jpg",
      },
      {
        User: "Parithabangal",
        Channelink: "https://www.youtube.com/@Parithabangal",
        Title: "Mind Relaxing 2023 ❤️ Mashup Lofi (Slowed X Reverb) #lofimashup",
        VideoLink: "https://www.youtube.com/watch?v=zMGs8TLeKnI",
        Category: "Gaming",
        Thumb: "https://i.ytimg.com/vi/zMGs8TLeKnI/hq720.jpg",
      },
      {
        User: "Naa Anveshana",
        Channelink: "https://www.youtube.com/@NaaAnveshana",
        Title: "Month End Paavangal | Parithabangal",
        VideoLink: "https://www.youtube.com/watch?v=Y9QUCpohyck",
        Category: "Music",
        Thumb: "https://i.ytimg.com/vi/Y9QUCpohyck/hq720.jpg",
      },
      {
        User: "T-Series",
        Channelink: "https://www.youtube.com/@tseries",
        Title: "Tonga Capital City And local Market",
        VideoLink: "https://www.youtube.com/watch?v=FsQAHUWRe1k",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/FsQAHUWRe1k/hq720.jpg",
      },
      {
        User: "Blank",
        Channelink: "https://www.youtube.com/shorts/Wb0YwrrJJvY",
        Title: "Ram Siya Ram (Hindi) Adipurush | Prabhas | Sachet-Parampara, Manoj Muntashir S | Om Raut | Bhushan K",
        VideoLink: "https://www.youtube.com/watch?v=GXWfue9VhTY",
        Category: "Gaming",
        Thumb: "https://i.ytimg.com/vi/GXWfue9VhTY/hq720.jpg",
      },
      {
        User: "Cricket Clock",
        Channelink: "https://www.youtube.com/@CricketClock",
        Title: "How Does Sony Keep Doing This?",
        VideoLink: "https://www.youtube.com/watch?v=PCp1BmME6QA",
        Category: "Music",
        Thumb: "https://i.ytimg.com/vi/PCp1BmME6QA/hq720.jpg",
      },
      {
        User: "DM - Desi Melodies",
        Channelink: "https://www.youtube.com/@DesiMelodies",
        Title: "India Vs Australia 1998 | SACHIN 5 Wickets for 32 vs Australia | Nail Bitting Bowling by Sachin😱🔥",
        VideoLink: "https://www.youtube.com/watch?v=_uk26swuAdE",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/_uk26swuAdE/hq720.jpg",
      },
      {
        User: "Trending",
        Channelink: "https://www.youtube.com/feed/trending",
        Title: "Kya Loge Tum | Akshay Kumar | Amyra Dastur | BPraak | Jaani | Arvindr Khaira | Zohrajabeen",
        VideoLink: "https://www.youtube.com/watch?v=cAMHx-m9oh8",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/cAMHx-m9oh8/hq720.jpg",
      },
      {
        User: "CarryMinati",
        Channelink: "https://www.youtube.com/@CarryMinati",
        Title: "MC SALMAN FT BIGG BOSS - CARRYMINATI",
        VideoLink: "https://www.youtube.com/watch?v=iFtH6g5HEVM",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/iFtH6g5HEVM/hq720.jpg",
      },
      {
        User: "DisneyPlus Hotstar",
        Channelink: "https://www.youtube.com/@hotstarOfficial",
        Title: "Hotstar Specials The Night Manager | Official Trailer Part 2 | 30th June | DisneyPlus Hotstar",
        VideoLink: "https://www.youtube.com/watch?v=Mysy-Dx2tY0",
        Category: "Gaming",
        Thumb: "https://i.ytimg.com/vi/Mysy-Dx2tY0/hq720.jpg",
      },
      {
        User: "Sony LIV",
        Channelink: "https://www.youtube.com/@SonyLIV",
        Title: "2nd ODI | Highlights | Afghanistan Tour Of Sri Lanka | 4th June 2023",
        VideoLink: "https://www.youtube.com/watch?v=UG8iV4Ii5-8",
        Category: "Other",
        Thumb: "https://i.ytimg.com/vi/UG8iV4Ii5-8/hq720.jpg",
      },
      {
        User: "Sandeep Maheshwari",
        Channelink: "https://www.youtube.com/@SandeepSeminars",
        Title: "Stop Wasting Your Time | Sandeep Maheshwari | Every Student Must Watch This Video | Hindi",
        VideoLink: "https://www.youtube.com/watch?v=oE4g4P41KLM",
        Category: "Music",
        Thumb: "https://i.ytimg.com/vi/oE4g4P41KLM/hq720.jpg",
      },
      {
        User: "Mythpat",
        Channelink: "https://www.youtube.com/@Mythpat",
        Title: "BUYING THE MOST EXPENSIVE FLYING BIKE IN GTA 5",
        VideoLink: "https://www.youtube.com/watch?v=JMH00UScHrM",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/JMH00UScHrM/hq720.jpg",
      },
      {
        User: "shreeman legend live",
        Channelink: "https://www.youtube.com/@shreemanlegendliveofficial",
        Title: "Ek Tournament Aisi bhi | Part 1 | BGMI Rising",
        VideoLink: "https://www.youtube.com/watch?v=3sMoOJT95eI",
        Category: "Music",
        Thumb: "https://i.ytimg.com/vi/3sMoOJT95eI/hq720.jpg",
      },
      {
        User: "MEDIA MARATHI",
        Channelink: "https://www.youtube.com/@MEDIAMARATHI1",
        Title: "३जून नाविन किर्तन 😀| #indurikarmaharaj इंदुरिकर महाराज किर्तन | indurikar Maharaj comedy kirtan |",
        VideoLink: "https://www.youtube.com/watch?v=ybnxSoeUsNo",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/ybnxSoeUsNo/hq720.jpg",
      },
      {
        User: "LIV Comedy",
        Channelink: "https://www.youtube.com/@LIVComedy",
        Title: "Jetha ने क्यों दी Bagha और Nattu Kaka को Party? | Taarak Mehta Ka Ooltah Chashmah | Jetha Chala US",
        VideoLink: "https://www.youtube.com/watch?v=XeAOX-Yb9uM",
        Category: "Gaming",
        Thumb: "https://i.ytimg.com/vi/XeAOX-Yb9uM/hq720.jpg",
      },
      {
        User: "shreeman legend live",
        Channelink: "https://www.youtube.com/@shreemanlegendliveofficial",
        Title: "Funny Pan Fight Or Rickshaw Safari | BGMI Rising",
        VideoLink: "https://www.youtube.com/watch?v=PcgSQhVH9OU",
        Category: "Music",
        Thumb: "https://i.ytimg.com/vi/PcgSQhVH9OU/hq720.jpg",
      },
      {
        User: "Judwaaz TV",
        Channelink: "https://www.youtube.com/@Judwaaz",
        Title: "EMIWAY - KING OF INDIAN HIP HOP | EXPLICIT | JUDWAAZ",
        VideoLink: "https://www.youtube.com/watch?v=W3keGaMG6uw",
        Category: "Other",
        Thumb: "https://i.ytimg.com/vi/W3keGaMG6uw/hq720.jpg",
      },
      {
        User: "Voilà! Digi",
        Channelink: "https://www.youtube.com/@voiladigi721",
        Title: "YAAD TERI AAYE BAAR BAAR: Sourav Joshi Vlogs & Pooh In Korea | Saaj Bhatt, Sandeep Batraa | Sad Song",
        VideoLink: "https://www.youtube.com/watch?v=400QfMKiCFs",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/400QfMKiCFs/hq720.jpg",
      },
      {
        User: "ProBoii",
        Channelink: "https://www.youtube.com/@proboii",
        Title: "I Tried Premium Playstore Games and Regretted it...",
        VideoLink: "https://www.youtube.com/watch?v=JY_KTm-iB3M",
        Category: "Music",
        Thumb: "https://i.ytimg.com/vi/JY_KTm-iB3M/hq720.jpg",
      },
      {
        User: "Smart Ai Money",
        Channelink: "https://www.youtube.com/@SmartAiMoney",
        Title: "ChatGPT: How I made $2,245 Within 15 Days | Earn $4k - $5k Copy Paste Strategy Part-2 | Chat GPT ai",
        VideoLink: "https://www.youtube.com/watch?v=IE9Pz_RkQqI",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/IE9Pz_RkQqI/hq720.jpg",
      },
      {
        User: "Rakesh Khatri",
        Channelink: "https://www.youtube.com/@rakeshkhatri01",
        Title: "Baahubali Kalakeya War Scene.",
        VideoLink: "https://www.youtube.com/watch?v=jv0VKri79c0",
        Category: "Gaming",
        Thumb: "https://i.ytimg.com/vi/jv0VKri79c0/hq720.jpg",
      },
      {
        User: "Ajay Pandey",
        Channelink: "https://www.youtube.com/@ajaypandey",
        Title: "ROYAL ENFIELD reaction in JAPAN II Indian in Japan II",
        VideoLink: "https://www.youtube.com/watch?v=apf9p7duPsc",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/apf9p7duPsc/hq720.jpg",
      },
      {
        User: "MIRROR NOW",
        Channelink: "https://www.youtube.com/@mirrornow",
        Title: "Odisha Train Accident | BJP Alleges 'Conspiracy', Congress Hits Back | English News | Odisha News",
        VideoLink: "https://www.youtube.com/watch?v=y6chhI49CwA",
        Category: "Other",
        Thumb: "https://i.ytimg.com/vi/y6chhI49CwA/hq720.jpg",
      },
      {
        User: "The Economic Times",
        Channelink: "https://www.youtube.com/@TheEconomicTimes",
        Title: "Odisha train accident: CBI formally takes over probe, team reaches at Balasore collision spot",
        VideoLink: "https://www.youtube.com/watch?v=wvjW19O83Wo",
        Category: "Gaming",
        Thumb: "https://i.ytimg.com/vi/wvjW19O83Wo/hq720.jpg",
      },
      {
        User: "India Today",
        Channelink: "https://www.youtube.com/@indiatoday",
        Title: "Odisha Train Tragedy: What Caused The Disaster: How Did A 'Fail-Safe' Track Management Fail?",
        VideoLink: "https://www.youtube.com/watch?v=gdzZTv5KkVM",
        Category: "Music",
        Thumb: "https://i.ytimg.com/vi/gdzZTv5KkVM/hq720.jpg",
      },
      {
        User: "Republic World",
        Channelink: "https://www.youtube.com/@RepublicWorld",
        Title: "Was it Sabotage in the Odisha train disaster? Niranjan & Shawan on Arnab's Debate",
        VideoLink: "https://www.youtube.com/watch?v=nbrdHG4-i7c",
        Category: "TV",
        Thumb: "https://i.ytimg.com/vi/nbrdHG4-i7c/hq720.jpg",
      },
    ],
  },
};


